services:
  redis1:
    image: redis
    container_name: token-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
