apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-user
  template:
    metadata:
      labels:
        app: spring-user
    spec:
      nodeSelector:
        role: worker2  # role=worker1 라벨이 있는 노드에서 실행
      containers:
        - name: spring-user
          image: choissu/ficket:springuser-latest
          ports:
            - containerPort: 9000
          env:
            - name: USER_MYSQL_URL
              value: "jdbc:mysql://ec2-13-209-11-36.ap-northeast-2.compute.amazonaws.com/ficket"
            - name: WORKER1_REDIS_HOST
              value: "ec2-13-209-11-36.ap-northeast-2.compute.amazonaws.com"
            - name: WORKER1_REDIS_PORT
              value: "6379"
          volumeMounts:
            - mountPath: /springdocker/Ficket/user  # 컨테이너 내에서 마운트될 위치
              name: user-volume
      volumes:
        - name: user-volume
          hostPath:
            path: /springdocker  # 실제 xvda1이 마운트된 경로
            type: Directory