server:
  port: 0

spring:
  application:
    name: ticketing-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

springdoc:
  api-docs:
    enabled: true
    path: "/ticketing-swagger/v3/api-docs"
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

encrypt:
  key-store:
    password: test1234
    alias: apiEncryptionKey
    location: classpath:/apiEncryptionKey.jks
