apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
      
  containers:
    - name: rabbitmq
      image: rabbitmq:3-management
      ports:
        - containerPort: 15672 # RabbitMQ Management UI
        - containerPort: 5672  # RabbitMQ Default Port
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: "rabbit"
        - name: RABBITMQ_DEFAULT_PASS
          value: "rabbit"
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
  volumes:
    - name: rabbitmq-data
      hostPath:
        path: /data/rabbitmq
        type: DirectoryOrCreate
