apiVersion: v1
kind: Pod
metadata:
  name: zookeeper1
  labels:
    app: zookeeper1
spec:
  containers:
    - name: zookeeper
      image: wurstmeister/zookeeper:latest
      ports:
        - containerPort: 2181
      env:
        - name: ZOOKEEPER_SERVER_ID
          value: "1"  # 서버 ID (단일 Pod일 경우 1로 설정)
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_ADMINSERVER_PORT
          value: "8080"
        - name: ZOOKEEPER_SERVERS
          value: "server.1=zookeeper:2888:3888"  # 내부 통신을 위한 서버 주소 (단일 Pod이므로 본인을 참조)
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
