apiVersion: v1
kind: Service
metadata:
  name: spring-discovery-service
spec:
  selector:
    app: spring-discovery
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
