apiVersion: v1
kind: Service
metadata:
  name: spring-gateway-service
spec:
  selector:
    app: spring-gateway
  ports:
    - protocol: TCP
      port: 9000      # 내부 클러스터 포트
      targetPort: 9000 # 컨테이너 내부 포트
      nodePort: 31098  # 외부에서 접근할 포트 (클러스터 노드 포트)
  type: NodePort
