apiVersion: v1
kind: Service
metadata:
  name: spring-config-service
spec:
  selector:
    app: spring-config
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
