spring:
  config:
    import: configserver:http://localhost:8888 # Config 서버 URL
  profiles:
    group:
      config-server: config-server # Config Server 프로파일
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

ZIPKIN_BASE_URL: http://127.0.0.1:9411
ZIPKIN_ENDPOINT: http://localhost:9411/api/v2/spans
REDIRECT_URI: http://localhost:8777/login/oauth2/code/kakao