"""Reinitialize migrations

Revision ID: 47ac312558f6
Revises: 
Create Date: 2025-02-17 10:26:39.286005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ac312558f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face',
    sa.Column('face_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.Column('face_img', sa.String(length=255), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('event_schedule_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('face_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face')
    # ### end Alembic commands ###
