"""Initial migration

Revision ID: 616c933b14ee
Revises: 
Create Date: 2024-12-28 13:28:02.497284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '616c933b14ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_record')
    op.drop_table('event')
    op.drop_table('stage_partition')
    op.drop_table('admin')
    op.drop_table('user')
    op.drop_table('settlement')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('UKm0fugnfyt092f4v0y2wahhgao')

    op.drop_table('orders')
    with op.batch_alter_table('refund_policy', schema=None) as batch_op:
        batch_op.drop_index('priority')

    op.drop_table('refund_policy')
    op.drop_table('ticket')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('UKtq5kr7wfeog5tjjr1eqtww5oh')

    op.drop_table('company')
    op.drop_table('account')
    op.drop_table('event_schedule')
    op.drop_table('seat_mapping')
    op.drop_table('stage_seat')
    op.drop_table('membership')
    op.drop_table('event_stage')
    op.drop_table('event_image')
    op.drop_table('event_genre')
    with op.batch_alter_table('face', schema=None) as batch_op:
        batch_op.alter_column('vector',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('face_img',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('event_schedule_id',
               existing_type=mysql.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face', schema=None) as batch_op:
        batch_op.alter_column('event_schedule_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('face_img',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('vector',
               existing_type=mysql.TEXT(),
               nullable=True)

    op.create_table('event_genre',
    sa.Column('event_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('genre', mysql.ENUM('뮤지컬', '스포츠', '아동_가족', '전시_행사', '콘서트', '클래식_무용'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name='FKl8pcu6617q7hxnm98o7if14k1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('event_image',
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('event_img_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('banner_mobile_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('banner_origin_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('banner_pc_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('poster_mobile_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('poster_origin_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('poster_pc_main1url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('poster_pc_main2url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('poster_pc_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('event_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name='FK9oirj7cwmu7k91vr0m13hqh8b'),
    sa.PrimaryKeyConstraint('event_img_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('event_stage',
    sa.Column('stage_size', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_stage_img', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sido', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sigungu', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('stage_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('street', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('stage_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('membership',
    sa.Column('baseline', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('benefit', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('membership_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('grade', mysql.ENUM('ROYAL', 'SPECIAL', 'VIP'), nullable=True),
    sa.PrimaryKeyConstraint('membership_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('stage_seat',
    sa.Column('x', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('y', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('seat_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('stage_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('seat_col', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('seat_row', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['event_stage.stage_id'], name='FKfi4q7lsd2no964dhr8sx3hi44'),
    sa.PrimaryKeyConstraint('seat_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seat_mapping',
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('event_schedule_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('partition_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('seat_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('seat_mapping_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_schedule_id'], ['event_schedule.event_schedule_id'], name='FK29h262oluaxcmke490kohw2u'),
    sa.ForeignKeyConstraint(['partition_id'], ['stage_partition.partition_id'], name='FKg4mpnvji6f8p81lam1cprfnpd'),
    sa.ForeignKeyConstraint(['seat_id'], ['stage_seat.seat_id'], name='FK3n0rtkypfhfaowql5vndpnxmi'),
    sa.PrimaryKeyConstraint('seat_mapping_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('event_schedule',
    sa.Column('round', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('event_date', mysql.TIMESTAMP(), nullable=False),
    sa.Column('event_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('event_schedule_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name='FKrnomdfxthbffuwwkj0oxyqd8h'),
    sa.PrimaryKeyConstraint('event_schedule_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account',
    sa.Column('balance', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('account_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('company',
    sa.Column('revenue', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('account_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('membership_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], name='FK75jxrkyqa7rjrx2sv72j7mnrf'),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.membership_id'], name='FK6ligxucdm6pyh3qpn0saylrs5'),
    sa.PrimaryKeyConstraint('company_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('UKtq5kr7wfeog5tjjr1eqtww5oh', ['account_id'], unique=True)

    op.create_table('ticket',
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('event_schedule_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('ticket_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('viewing_status', mysql.ENUM('NOT_WATCHED', 'WATCHED', 'DELETED'), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('refund_policy',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cancellation_period', mysql.VARCHAR(length=255), nullable=False, comment='취소 기간'),
    sa.Column('refund_fee_description', mysql.VARCHAR(length=255), nullable=False, comment='취소 수수료 설명'),
    sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=False, comment='우선순위 (적용 순서 정의)'),
    sa.PrimaryKeyConstraint('id'),
    comment='환불 정책 테이블',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='환불 정책 테이블',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('refund_policy', schema=None) as batch_op:
        batch_op.create_index('priority', ['priority'], unique=True)

    op.create_table('orders',
    sa.Column('order_price', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('refund_price', mysql.DECIMAL(precision=38, scale=2), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('order_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payment_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('order_status', mysql.ENUM('CANCELLED', 'COMPLETED', 'INPROGRESS', 'REFUNDED'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], name='FKsesssrpdbpddyr7a4t4nyiy7p'),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('UKm0fugnfyt092f4v0y2wahhgao', ['ticket_id'], unique=True)

    op.create_table('settlement',
    sa.Column('settlement_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('net_supply_amount', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('refund_value', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('service_fee', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('settlement_status', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.Column('settlement_value', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('supply_value', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('vat', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('settlement_record_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`settlement_status` between 0 and 2)', name='settlement_chk_1'),
    sa.ForeignKeyConstraint(['settlement_record_id'], ['settlement_record.settlement_record_id'], name='FKbhb43s7qg0nldyrjp8hdkmxwf'),
    sa.PrimaryKeyConstraint('settlement_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('birth', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('social_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`gender` between 0 and 1)', name='user_chk_1'),
    sa.CheckConstraint('(`state` between 0 and 3)', name='user_chk_2'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('role', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.Column('admin_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pw', mysql.VARCHAR(length=255), nullable=False),
    sa.CheckConstraint('(`role` between 0 and 2)', name='admin_chk_1'),
    sa.PrimaryKeyConstraint('admin_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('stage_partition',
    sa.Column('partition_price', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('event_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('partition_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('partition_name', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name='FKe440hspj5rt1d5r22uiu0adew'),
    sa.PrimaryKeyConstraint('partition_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('event',
    sa.Column('reservation_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('running_time', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admin_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('event_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('stage_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ticketing_time', mysql.TIMESTAMP(), nullable=False),
    sa.Column('sub_title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('age', mysql.ENUM('만_12세_이상', '만_15세_이상', '만_7세_이상', '전체관람가', '청소년_관람불가'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['event_stage.stage_id'], name='FKmj14wtkcm2ug17mpq8smtfg8k'),
    sa.PrimaryKeyConstraint('event_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('settlement_record',
    sa.Column('settlement_record_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('event_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('settlement_status', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('total_net_supply_amount', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('total_refund_value', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('total_service_fee', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('total_settlement_value', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('total_supply_amount', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.Column('total_vat', mysql.DECIMAL(precision=38, scale=2), nullable=False),
    sa.CheckConstraint('(`settlement_status` between 0 and 0)', name='settlement_record_chk_1'),
    sa.PrimaryKeyConstraint('settlement_record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
