name: Jira Update on Commit to Dev

on:
  push:
    branches:
      - dev  # 'dev' 브랜치로 푸시될 때마다 실행됨

jobs:
  update-jira-status:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Extract commit message
      id: commit_message
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "COMMIT_MESSAGE=$COMMIT_MSG" >> $GITHUB_ENV
    
    - name: Check for issue key and #done
      id: check_done
      run: |
        # 정규식으로 'SCRUM-'으로 시작하는 이슈 키와 #done을 찾아서 추출
        if [[ "${{ env.COMMIT_MESSAGE }}" =~ \#(SCRUM-[0-9]+)\s\#done ]]; then
          ISSUE_KEY="${BASH_REMATCH[1]}"  # SCRUM- 접두사와 숫자를 포함한 이슈 키 추출
          echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV
          echo "DONE=true" >> $GITHUB_ENV
        else
          echo "No valid issue key or #done detected."
          echo "DONE=false" >> $GITHUB_ENV
    
    - name: Update Jira Issue
      if: env.DONE == 'true'
      run: |
        curl -u ${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
        -X POST \
        -H "Content-Type: application/json" \
        --data '{
          "transition": { "id": "31" }
        }' \
        "https://ficket.atlassian.net/rest/api/2/issue/${{ env.ISSUE_KEY }}/transitions"

      
      env:
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
